// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProVMSIT15.Data;

#nullable disable

namespace ProVMSIT15.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521010122_AddAuditAndSLA")]
    partial class AddAuditAndSLA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProVMSIT15.Models.AppUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProVMSIT15.Models.Contract", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ContractTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NegotiationNotes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VendorID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("ProVMSIT15.Models.ContractItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ContractID")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("NegotiatedUnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("VendorItemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ContractID");

                    b.HasIndex("VendorItemID");

                    b.ToTable("ContractItems");
                });

            modelBuilder.Entity("ProVMSIT15.Models.DepartmentBudget", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("AllocatedBudget")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentCode", "FiscalYear")
                        .IsUnique();

                    b.ToTable("DepartmentBudgets");
                });

            modelBuilder.Entity("ProVMSIT15.Models.FinancialAuditTrail", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("JWTSignatureHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MachineIPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("PayloadAfter")
                        .HasColumnType("longtext");

                    b.Property<string>("PayloadBefore")
                        .HasColumnType("longtext");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SystemTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AuditID");

                    b.HasIndex("UserID");

                    b.ToTable("FinancialAuditTrails");
                });

            modelBuilder.Entity("ProVMSIT15.Models.InAppNotification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NotificationText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TargetUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TargetUserID");

                    b.ToTable("InAppNotifications");
                });

            modelBuilder.Entity("ProVMSIT15.Models.PurchaseRequisition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinanceSubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsEncumbered")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("POIssuedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RequesterID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCalculatedAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.HasIndex("RequesterID");

                    b.ToTable("PurchaseRequisitions");
                });

            modelBuilder.Entity("ProVMSIT15.Models.SLAMilestoneLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogID"));

                    b.Property<decimal?>("DurationHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime?>("EndTimestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReferenceID")
                        .HasColumnType("int");

                    b.Property<string>("SLABreachStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LogID");

                    b.ToTable("SLAMilestoneLogs");
                });

            modelBuilder.Entity("ProVMSIT15.Models.SupplierEvaluation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CommunicationStars")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliverySpeedStars")
                        .HasColumnType("int");

                    b.Property<int>("ItemConditionStars")
                        .HasColumnType("int");

                    b.Property<string>("PerformanceComments")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("RequisitionID")
                        .HasColumnType("int");

                    b.Property<int?>("VendorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RequisitionID")
                        .IsUnique();

                    b.HasIndex("VendorID");

                    b.ToTable("SupplierEvaluations", t =>
                        {
                            t.HasCheckConstraint("CK_Communication", "`CommunicationStars` BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_DeliverySpeed", "`DeliverySpeedStars` BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_ItemCondition", "`ItemConditionStars` BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("ProVMSIT15.Models.Vendor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DocumentVaultURL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("LinkedUserID")
                        .HasColumnType("int");

                    b.Property<string>("OperationalStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("LinkedUserID");

                    b.HasIndex("TaxID")
                        .IsUnique();

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("ProVMSIT15.Models.VendorItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VendorID");

                    b.ToTable("VendorItems");
                });

            modelBuilder.Entity("ProVMSIT15.Models.Contract", b =>
                {
                    b.HasOne("ProVMSIT15.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ProVMSIT15.Models.ContractItem", b =>
                {
                    b.HasOne("ProVMSIT15.Models.Contract", "Contract")
                        .WithMany("Items")
                        .HasForeignKey("ContractID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProVMSIT15.Models.VendorItem", "VendorItem")
                        .WithMany()
                        .HasForeignKey("VendorItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("VendorItem");
                });

            modelBuilder.Entity("ProVMSIT15.Models.FinancialAuditTrail", b =>
                {
                    b.HasOne("ProVMSIT15.Models.AppUser", "Actor")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("ProVMSIT15.Models.InAppNotification", b =>
                {
                    b.HasOne("ProVMSIT15.Models.AppUser", "TargetUser")
                        .WithMany("Notifications")
                        .HasForeignKey("TargetUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("ProVMSIT15.Models.PurchaseRequisition", b =>
                {
                    b.HasOne("ProVMSIT15.Models.VendorItem", "Item")
                        .WithMany("Requisitions")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProVMSIT15.Models.AppUser", "Requester")
                        .WithMany("Requisitions")
                        .HasForeignKey("RequesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("ProVMSIT15.Models.SupplierEvaluation", b =>
                {
                    b.HasOne("ProVMSIT15.Models.PurchaseRequisition", "Requisition")
                        .WithOne("Evaluation")
                        .HasForeignKey("ProVMSIT15.Models.SupplierEvaluation", "RequisitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProVMSIT15.Models.Vendor", "Vendor")
                        .WithMany("Evaluations")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Requisition");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ProVMSIT15.Models.Vendor", b =>
                {
                    b.HasOne("ProVMSIT15.Models.AppUser", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedUser");
                });

            modelBuilder.Entity("ProVMSIT15.Models.VendorItem", b =>
                {
                    b.HasOne("ProVMSIT15.Models.Vendor", "Vendor")
                        .WithMany("Items")
                        .HasForeignKey("VendorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ProVMSIT15.Models.AppUser", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Requisitions");
                });

            modelBuilder.Entity("ProVMSIT15.Models.Contract", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProVMSIT15.Models.PurchaseRequisition", b =>
                {
                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("ProVMSIT15.Models.Vendor", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProVMSIT15.Models.VendorItem", b =>
                {
                    b.Navigation("Requisitions");
                });
#pragma warning restore 612, 618
        }
    }
}
